### ISSUE TITLE
First steps with Kanban board

### ISSUE THREAD

**Issue by DavidEspinoG** [DavidEspinoG/spacexhub#22]
## Starting the project
[Link to the Kanban board](https://github.com/DavidEspinoG/spacexhub/projects/1)
There are two members in the team
@Alejandro-Bernal-M  and @DavidEspinoG

**Comment by OyePriscilla** [comment]
Hi @DavidEspinoG and @Alejandro-Bernal-M 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Added link to GitHub project ✔️
Listed information about the number of people in the group ✔️

## Required Changes ♻️

- [ ] Please kindly assign the group task to any member of the group fairly; more so I couldn't find this task on your Kanban board. 👇 
<img width="240" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/230943521-82063f49-3d23-4bdd-a1b0-cba4dee60b68.png">

**Note: You suppose to have a total of 17 tasks assigned on you Kanban board.**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DavidEspinoG** [comment]
Oh, ok. I think the script didn’t copy all the assignments correctly. We will manually copy the missing tasks

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your project is complete!  Congratulations!  🎉💯🌟 

## Highlights 👍
🎲 Fair distribution of tasks!

Cheers! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
